# The main entry point of your workflow.
# After configuring, running snakemake -n should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"


configfile: "config/config.yaml"


pepfile: config["pepfile"]


include: "rules/common.smk"
include: "rules/example.smk"


# The first rule should define the default target files
# Subsequent target rules can be specified below. They should start with all_*.
rule all:
    input:
        expand(
            "results/test-{sample}-{url}.txt",
            zip,
            sample=get_samples(),
            url=get_urls(),
        ),
